a = float(input())
b = float(input())
c = float(input())
d = float(input())
e = float(input())
f = float(input())
x = (f * b - d * e) / (b * c - d * a)
y = (f * a - c * e) / (a * d - c * b)
print(x, y)
